<a href="https://colab.research.google.com/github/MoonEeSun/Artificial_Intelligence/blob/main/2021_AI_2_pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2-1 파이토치 패키지의 기본 구성
- torch : 텐서 등의 다양한 수학 함수 포함, numpy와 유사한 구조
- torch.autograd : 자동 미분을 위한 함수
- torch.nn : 신경망을 구축하기 위한 다양한 데이터 구조나 layer 정의
  - RNN, LSTM 과 같은 layer / ReLU와 같은 활성함수, MSELoss와 같은 손실 함수
- torch.optim : 파라미터 최적화 알고리즘 구현
  - 확률적 경사 하강법 : Stochastic Gradient Descent, SGD
- torch.utils.data : SGD의 반복 연산을 실행할 때 사용하는 '미니 배피용 유틸리티 함수' 포함
- torch.onnx : ONNX의 포맷으로 모델을 export할 때 사용
  - ONNX는 서로 다른 딥러닝 프레임워크 간 모델을 공유할 때 사용


# 2-2. 텐서 조작하기(Tensor Manipulation) 1
- 벡터, 행렬, 텐서의 개념에 대해서 이해
- Numpy와 파이토치로 벡터, 행렬, 텐서를 다루는 방법 이해

### 1. 벡터, 행렬, 텐서
- 1차원 : 벡터(vector)
- 2차원 : 행렬(Matrix)
- 3차원 : 텐서(Tensor)
  - 2D Tensor
    - 2차원의 텐서 크기 = batch_size(행의 크기) * dimension(열의 크기)
      - Ex) 훈련데이터 하나의 크기 = 256 (= 벡터의 차원 ), 훈련데이터의 개수 3000개 => 전체 훈련 데이터 크기 = 3000 X 256, 3000개에서 64개씩 꺼내서 처리한다면 => batch_size = 64, 컴퓨터가 한 번에 처리하는 2D 텐서의 크기 = 64 x 256
    - 3D Tensor : 일반적으로 이미지, 영상처리 할 때 사용
      - 3차원 텐서 크기 = batch_size, width, height
      - 자연어 처리 = batch_size, 문장 길이, 단어 벡터 차원

In [ ]:
# 자연어 처리의 예시
NLP_data = [["나는 사과를 좋아해"], ["나는 바나나를 좋아해"], ["나는 사과를 싫어해"], ["나는 바나나를 싫어해"]]

# 단어 별로 나눠주기 => 4 x 3의 크기를 가지는 2D tensor
NLP_data_split = [['나는', '사과를', '좋아해'], ['나는', '바나나를', '좋아해'], ['나는', '사과를', '싫어해'], ['나는', '바나나를', '싫어해']]

# 각 단어를 벡터로 만들기 => 4 x 4 x 3의 크기를 가지는 3D tensor
## '나는' = [0.1, 0.2, 0.9]
## '사과를' = [0.3, 0.5, 0.1]
## '바나나를' = [0.3, 0.5, 0.2]
## '좋아해' = [0.7, 0.6, 0.5]
## '싫어해' = [0.5, 0.6, 0.7]
NLP_data_vector = [[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
                  [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]],
                  [[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
                  [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]

# batch_size를 2로 => 각 batch의 tensor 크기는 2 x 3 x 3 == (batch_size, 문장 길이, 단어 벡터 차원의 크기)
## 첫번째 배치 #1
# [[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
#  [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]]
## 두번째 배치 #2
# [[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
# [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]

### 2. numpy
#### 1) 1차원 텐서인 vector

In [ ]:
# 넘파이로 텐서 만들기(벡터와 행렬 만들기)
import numpy as np

t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)
print('Rank of t: ', t.ndim) # 1차원 텐서인 벡터의 차원
print('Shape of t: ', t.shape) # 1차원 텐서인 벡터의 크기

# numpy
print('t[0] t[1], t[-1] = ', t[0], t[1], t[-1])

[0. 1. 2. 3. 4. 5. 6.]
Rank of t:  1
Shape of t:  (7,)
t[0] t[1], t[-1] =  0.0 1.0 6.0


#### 2) 2차원 텐서인 행렬

In [ ]:
t = np.reshape(range(1, 13), (4, 3))
print(t)
# print('Rank of t: ', t.dim)
print('Shape of t: ', t.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape of t:  (4, 3)


#### 3) pytorch tensor

In [ ]:
import torch

# 1차원 tensor
t_1 = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t_1)
print(t_1.dim()) # 차원
print(t_1.shape) # shape
print(t_1.size()) # shape

print(t_1[0], t_1[1], t_1[-1])  # 인덱스로 접근
print(t_1[2:5], t_1[4:-1])    # 슬라이싱 - a:b => a부터 b-1까지
print(t_1[:2], t_1[3:])       # 슬라이싱

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [ ]:
# 2차원 tensor
t_2 = torch.FloatTensor([[1., 2., 3.],
                         [4., 5., 6.],
                         [7., 8., 9.],
                         [10., 11., 12.]])
print(t_2)
print(t_2.dim()) # 차원
print(t_2.shape) # shape
print(t_2.size()) # shape

print(t_2[:, 1]) # 첫번째 차원을 전체 선택, 두번째 차원에서 1번째 것만 가져옴
print(t_2[:, 1].size())

print(t_2[:, :-1]) # 첫번째 차원은 전체 선택, 두번째 차원에서 마지막 빼고 전부 가져옴
print(t_2[:, :-1].size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])
torch.Size([4, 2])


#### 브로드캐스팅 : 크기가 다른 행렬 또는 텐서에 대해서 사칙연산을 수행하는 경우, 자동으로 크기를 맞춰서 연산

In [ ]:
# 크기가 같은 텐서에 대해서 사칙연산 수행

m1 = torch.FloatTensor([[3, 3]]) # size = (1, 2)
m2 = torch.FloatTensor([[2, 2]]) # size = (1, 2)
print(m1+m2)

tensor([[5., 5.]])


In [ ]:
# vector + scalar

m1 = torch.FloatTensor([[1, 2]]) 
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [ ]:
# 2x1 vector + 1x2 vector
m1 = torch.FloatTensor([[1, 2]]) # => [[1, 2], [1, 2]]
m2 = torch.FloatTensor([[3], [4]]) # => [[3, 3], [4, 4]]
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


#### 자주 사용되는 기능
##### 1. 행렬 곱셈과 곱셈의 차이
- 파이토치 텐서의 행렬 곱셈은 matmul()을 통해 수행
- *, .mul()은 브로드캐스팅 된 곱셈 결과

In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2. shape)
print(m1.matmul(m2))
print(m1 * m2) # 브로드캐스팅 되어서 곱해짐 m2 => [[1, 1], [2, 2]]
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


##### 2. 평균 :: .mean(dim = )

In [ ]:
print(m1)
print(m1.mean())

print(m1.mean(dim = 0)) # 첫번째 차원을 제거한 후 나머지에서 평균 (1, 3의 평균 / 2, 4의 평균)
print(m1.mean(dim = 1)) # 두번째 차원을 제거한 후 나머지에서 평균 (1, 2의 평균 / 3, 4의 평균)
print(m1.mean(dim = -1)) # 마지막 차원을 제거 == 열의 차원을 제거

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


##### 3) 덧셈 :: .sum(dim=)

In [ ]:
print(m1)
print(m1.sum()) # 원소 전체에 대한 덧셈
print(m1.sum(dim = 0)) # 행을 제거
print(m1.sum(dim = 1)) # 열을 제거
print(m1.sum(dim = -1)) # 마지막 차원을 제거 == 열을 제거

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


##### 4) Max, ArgMax
- Max : 원소의 최대값
- ArgMax : 최대값을 가진 인덱스

In [ ]:
print(m1)

print(m1.max())

print(m1.max(dim=0)) # argmax도 함께 return :: 행 제거 => (1, 2) 텐서를 생성
# 첫번째 열에서 3의 인덱스는 1이었습니다. 두번째 열에서 4의 인덱스는 1이었습니다. 그러므로 [1, 1]이 리턴됩니다.
print('Max: ', m1.max(dim=0)[0])
print('Argmax: ', m1.max(dim=0)[1])

print(m1.max(dim=1)) # 열 제거 => (2, 1) 텐서 생성
print(m1.max(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


# 2-3. 텐서 조작하기(Tensor Manipulation) 2
##### 4) 뷰(view) - 원소의 수를 유지하면서 텐서의 크기 변경
- 뷰(view)는 numpy에서 reshape와 같은 역할
- .view([])
###### 4-1) 3차원 텐서에서 2차원 텐서로 변경

In [ ]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

print(ft.shape) # 2 x 2 x 3 인 3차원 텐서

torch.Size([2, 2, 3])


In [ ]:
print(ft.view([-1, 3])) # -1: 첫번째 차원은 잘 모르겠음. 두번째 차원은 3으로 
print(ft.view([-1, 3]).shape) # :: 3차원 텐서를 2차원으로 변경하되 (?, 3)의 크기로 변환

## (2, 2, 3) -> (2 x 2, 3) -> (4, 3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


##### 3차원 텐서의 크기 변경
- 3차원 텐서에서 차원은 유지하되, 크기를 바꾸는 작업

In [ ]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


##### 5) squeeze : 1인 차원을 제거
- .squeeze()

In [ ]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


##### 6) Unsqueeze : 특정 위치에 1인 차원을 추가
- .unsqueeze()

In [ ]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

print(ft.unsqueeze(0)) # 0 : 첫번째 차원 => (1, 3)
print(ft.unsqueeze(0).shape)

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
# unsqueeze와 view가 동일한 결과를 만들어내는 예시
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(ft.unsqueeze(1)) # 두번째 차원에 1을 추가 => (3, 1)
print(ft.unsqueeze(1).shape)

print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


##### 7) 타입 캐스팅
- 자료형을 변환하는 것
- ex) 32비트 부동소수점 torch.FloatTensor
- ex) 64비트 부동소수점 torch.LongTensor
- ex) GPU를 위한 연산 자료형 torch.cuda.FloatTensor

In [ ]:
# long타입의 tensor
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

# tensor에 .float()을 붙이면 바로 float형으로 변환
print(lt.float()) 

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [ ]:
# byte타입의 tensor
bt = torch.ByteTensor([True, False, False, True])
print(bt)

# tensor에 .long()을 붙이면 long타입의 텐서로 변환
print(bt.long())
# tensor에 .float()을 붙이면 float타입의 텐서로 변환
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


##### 8) 연결(concatenate)
- 두 텐서를 연결하는 방법 :: torch.cat([], dim=)

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim = 0)) # dim = 0 :: 첫번째 차원을 늘리기 => (4 x 2)
print(torch.cat([x, y], dim = 1)) # dim = 1 :: 두번째 차원을 늘리기 => (2 x 4)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


##### 9) stacking
- concat과 같이 쌓는다는 의미 :: torch.stack([], dim = )

In [ ]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z])) # 3개의 벡터가 순차적으로 쌓여 3 x 2가 됨 - 위로 쌓아진 형태
# print(torch.cat([x.unsqueeze(0), y.unsqqueeze(0), z.unsqueeze(0)], dim = 0))
# unsqueeze(0)을 함으로써 (2,)크기가 (1, 2)크기의 2차원 텐서로 변경

print(torch.stack([x, y, z], dim = 1)) # 두번째 차원이 증가하도록 :: 2 x 3 텐서가 됨 - 옆으로 쌓아진 형태

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


##### 10) ones_like, zeros_like
- ones_like : 0으로 채워진 텐서
  - torch.ones_like()
- zeros_like : 1로 채워진 텐서
  - torch.zeros_like()

In [ ]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


##### 11) In-place Operation (덮어쓰기 연산)
  - .mul_()

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]]) # 2 x 2 tensor
print(x.mul(2.)) # 2를 곱한 결과
print(x) # 2를 곱했어도 저장되지는 않았음

print(x.mul_(2.)) # 결과를 덮어쓰기
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


# 2-4. 파이썬 클래스(class)
##### 1) 함수(function)과 클래스(class) 차이

In [ ]:
# 함수로 덧셈기 구현
result = 0

def add(num):
  global result # 기존의 result에 함수의 인자로 온 num을 더하고 return
  result += num
  return result

print(add(3)) # 0 + 3
print(add(4)) # 3 + 4

3
7


In [ ]:
# 함수로 두 개의 덧셈기 구현
## 독립적인 두 개의 덧셈기를 구현. 하나의 함수는 한 개의 독립적인 덧셈기 이기 때문에 2개의 함수를 만들어야 함

result1 = 0
result2 = 0

def add1(num):
  global result1
  result1 += num
  return result1

def add2(num):
  global result2
  result2 += num
  return result2


print(add1(3))
print(add1(4))
print(add2(3))
print(add2(7))

# 서로의 값에 영향을 미치지 않고 다른 연산을 수행하고 있음

3
7
3
10


함수가 하나의 기계라면, class는 기계를 생산해 내는 틀 느낌
- 함수 : 빵
- class : 빵틀

In [ ]:
# class로 덧셈기 구현

class Calculator:
  def __init__(self): # 객체를 생성할 시 호출될 때 실행되는 초기화 함수 => 생성자라고 함
    self.result = 0
  
  def add(self, num): # 객체 생성 후 사용할 수 있는 함수
    self.result += num
    return self.result

In [ ]:
cal1 = Calculator()
cal2 = Calculator()

print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

3
7
3
10
