<a href="https://colab.research.google.com/github/MoonEeSun/Artificial_Intelligence/blob/main/2021_AI_HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 과제2. 선형회귀 진행
1. 관련 모듈 import
2. data load
3. model 불러오기 -> 방법(3)
  1. 직접 w, b, cost 작성
  2. nn.Module 이용
  3. class 이용
4. Optimizer 정의
5. epoch로 train
  - H(x) 정의
  - cost 함수 정의
  - cost로 H(x) 개선
    - optimizer gradient 0으로 초기화
    - cost 함수의 미분값 구하기
    - W,b 업데이트

### 1. 관련 모듈 import 및 random seed 고정

In [ ]:
# import
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

# random seed 1로 고정
torch.manual_seed(1)

### 2. data load

In [ ]:
# data load
X = np.array([[-10, 0, -8, -8], [-4, -3,  9,  3], [-7,  9, 10,  4], [-6, -4,  2,  3], [-6, -9, -9,  1], 
              [-2,  5, -7, -2], [-9, -2, -3, -3], [9,  -4,  6,  4], [9,  -1, -9, -6], [1, -9, -11,  3]])
Y = np.array([-2.0, -53.9, -21.1, -36.7, -15.2, 42.9, -25.7, -11.4, 56.0, 7.2])

print(X.shape)
print(Y.shape)


# tensor로 변환
x_train = torch.FloatTensor(X)
y_train = torch.FloatTensor(Y).unsqueeze(1)

print(x_train.shape)
print(y_train.shape)

(10, 4)
(10,)
torch.Size([10, 4])
torch.Size([10, 1])


### 3. model 불러오기

1) w, b, cost 작성

In [ ]:
W = torch.zeros((4,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

2) nn.Module 사용

In [ ]:
model = nn.Linear(4, 1)

3) class로 구현

In [ ]:
class MultivariateLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(4, 1)

  def forward(self, x):
    return self.linear(x)


model = MultivariateLinearRegressionModel()

### 4. optimizer 정의

In [ ]:
# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-3)

### 5. train

In [ ]:
nb_epochs = 5000
for epochs in range(nb_epochs+1):

  # H(x)
  prediction = model(x_train)

  # cost function
  cost = F.mse_loss(prediction, y_train)

  # cost로 H(x)개선
  ## optimizer gradient 0으로 초기화
  optimizer.zero_grad()
  ## cost 미분값 구하기
  cost.backward()
  ## W, b 값 업데이트
  optimizer.step()

  if epochs % 200 == 0:
    print('Epoch {:4d}/{} Cost : {:6f}'.format(epochs, nb_epochs, cost.item()))


print(list(model.parameters()))

Epoch    0/5000 Cost : 1037.261230
Epoch  200/5000 Cost : 6.372836
Epoch  400/5000 Cost : 5.128925
Epoch  600/5000 Cost : 4.849803
Epoch  800/5000 Cost : 4.700386
Epoch 1000/5000 Cost : 4.617626
Epoch 1200/5000 Cost : 4.571750
Epoch 1400/5000 Cost : 4.546322
Epoch 1600/5000 Cost : 4.532220
Epoch 1800/5000 Cost : 4.524405
Epoch 2000/5000 Cost : 4.520077
Epoch 2200/5000 Cost : 4.517669
Epoch 2400/5000 Cost : 4.516337
Epoch 2600/5000 Cost : 4.515602
Epoch 2800/5000 Cost : 4.515193
Epoch 3000/5000 Cost : 4.514971
Epoch 3200/5000 Cost : 4.514838
Epoch 3400/5000 Cost : 4.514771
Epoch 3600/5000 Cost : 4.514732
Epoch 3800/5000 Cost : 4.514708
Epoch 4000/5000 Cost : 4.514699
Epoch 4200/5000 Cost : 4.514695
Epoch 4400/5000 Cost : 4.514686
Epoch 4600/5000 Cost : 4.514687
Epoch 4800/5000 Cost : 4.514687
Epoch 5000/5000 Cost : 4.514684
[Parameter containing:
tensor([[ 2.9030,  3.9810, -3.7670,  0.3561]], requires_grad=True), Parameter containing:
tensor([0.9343], requires_grad=True)]


### 6. test


In [ ]:
test_var1 = torch.FloatTensor([-10, 0, -8, -8])
pred_y1 = model(test_var1)

print("훈련 후 입력이 -10, 0, -8, -8일 때의 예측값: ", pred_y1)
print(list(model.parameters()))

훈련 후 입력이 -10, 0, -8, -8일 때의 예측값:  tensor([-0.8088], grad_fn=<AddBackward0>)
[Parameter containing:
tensor([[ 2.9030,  3.9810, -3.7670,  0.3561]], requires_grad=True), Parameter containing:
tensor([0.9343], requires_grad=True)]


In [ ]:
test_var = torch.FloatTensor([-4, -3,  9,  3])
pred_y = model(test_var)

print("훈련 후 입력이 -4, -3,  9,  3일 때의 예측값: ", pred_y)
print(list(model.parameters()))

훈련 후 입력이 -4, -3,  9,  3일 때의 예측값:  tensor([-55.4555], grad_fn=<AddBackward0>)
[Parameter containing:
tensor([[ 2.9030,  3.9810, -3.7670,  0.3561]], requires_grad=True), Parameter containing:
tensor([0.9343], requires_grad=True)]
